### PR TITLE
fix security issues, other minor changes

### LINKED ISSUE #1: Failing build
Noticed recent builds on dockerhub are failing, tried it myself and saw the same thing.  Here's why:

```
Step 3/9 : RUN locale-gen en_US en_US.UTF-8     && dpkg-reconfigure locales     && ln -sf /usr/share/zoneinfo/UTC /etc/localtime     && echo 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' > /etc/apt/sources.list.d/mongodb-org-3.2.list     && echo 'deb http://repo.pritunl.com/stable/apt xenial main' > /etc/apt/sources.list.d/pritunl.list     && apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 42F3E95A2C4F08279C4960ADD68FA50FEA312927     && apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A     && apt-get update -q     && apt-get upgrade -y -q     && apt-get dist-upgrade -y -q     && apt-get -y install pritunl mongodb-org iptables     && apt-get clean     && apt-get -y -q autoclean     && apt-get -y -q autoremove     && rm -rf /tmp/*
 ---> Running in e01856bda59b
/bin/sh: 1: locale-gen: not found
```

I'll look into it, just wanted to capture the issue first.

### PR DESCRIPTION
**Pull request by gaieges**
Fixes #1 .. also pulls from openvpn repo which has the updates for big security issues here:

https://guidovranken.wordpress.com/2017/06/21/the-openvpn-post-audit-bug-bonanza/

Follows approach documented here:
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

Updates ports to be more accurate based on what pritunl comes with out of the box now.

### CODE REVIEW

**Comment by gaieges** [comment]
Hmm taking a closer glance at this .. i'm not sure your port 9700 in the config is respected, have you seen that spin up the pritunl server up on that port?  I only see it on 80 and 443.

Don't merge this yet lets resolve that and readme changes first.

**Comment by gaieges** [comment]
Yeah ok .. so the port value isn't respected in the `/etc/pritunl.conf`:

```bash
root@b02bc15025a8:/# cat /etc/pritunl.conf
    {
        "mongodb_uri": "mongodb://localhost:27017/pritunl",
        "server_key_path": "/var/lib/pritunl/pritunl.key",
        "log_path": "/var/log/pritunl.log",
        "static_cache": true,
        "server_cert_path": "/var/lib/pritunl/pritunl.crt",
        "temp_path": "/tmp/pritunl_%r",
        "bind_addr": "0.0.0.0",
        "debug": true,
        "www_path": "/usr/share/pritunl/www",
        "local_address_interface": "auto",
        "port": 9700
    }
root@b02bc15025a8:/# netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.11:44566        *:*                     LISTEN
tcp        0      0 localhost:9756          *:*                     LISTEN
tcp        0      0 localhost:27017         *:*                     LISTEN
tcp6       0      0 [::]:80                 [::]:*                  LISTEN
tcp6       0      0 [::]:443                [::]:*                  LISTEN
udp        0      0 127.0.0.11:52245        *:*
```

My thought is to just do away with the port option and just use 80/443.  Thoughts?

**Comment by jippi** [comment]
I think it looks good! 9700 is just what old versions used :)

**Comment by jippi** [comment]
Thanks for the PR ! nice improvements and nice to know it's more secure now :)

**Pull request merged**
